Repository PatientPaI/patientpal-frontend, pull requests merged in 2024-06, with the labels that each got.

#4 [feat] : AuthLayout 컴포넌트 마크업 및 스타일링
  .eslintrc.cjs
  .prettierrc.cjs
  package.json
  src/components/layout/AuthLayout.tsx
  src/index.css
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: Feature

#7 Feature/로그인페이지 마크업 및 스타일링
  public/assets/checked.svg
  public/assets/hide.svg
  public/assets/logo_google.svg
  public/assets/logo_kakao.svg
  public/assets/logo_naver.png
  public/assets/logo_naver.svg
  public/assets/show.svg
  public/assets/unchecked.svg
  src/App.tsx
  src/components/Form/FormCheckbox.tsx
  src/components/Form/FormInput.tsx
  src/components/Form/index.ts
  src/components/common/Button.tsx
  src/components/common/SocialLoginButtonSet.tsx
  src/pages/Login.tsx
  src/pages/SignIn.tsx
  src/utils/getUserIdFromLocalStorage.ts
Labels: Feature, Chore, Add

#9 Feature/회원가입 페이지 마크업 및 스타일링
  package.json
  public/assets/caregiver_both.png
  public/assets/patient.png
  public/assets/patient_both.png
  src/App.tsx
  src/components/Form/FormCheckbox.tsx
  src/components/Form/FormInput.tsx
  src/components/common/Button.tsx
  src/components/common/SocialLoginButtonSet.tsx
  src/components/layout/AuthLayout.tsx
  src/index.css
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.css
  src/pages/auth/SignUp.tsx
  src/pages/auth/index.ts
  yarn.lock
Labels: Feature, Refactor, Design, Add

#11 [feat] : 홈 화면 마크업 및 스타일링
  package.json
  public/assets/caregiver_both.png
  public/assets/icon-contract.png
  public/assets/icon-notice.png
  public/assets/icon-ranking1.png
  public/assets/icon-ranking2.png
  public/assets/icon-ranking3.png
  public/assets/logo-footer.png
  public/assets/logo-main.png
  public/assets/main-banner.png
  public/assets/right circle icon.png
  src/components/Home/Card.tsx
  src/components/Home/MainTitleIndex.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/SideBarItems.tsx
  src/components/layout/Layout.tsx
  src/pages/Home.tsx
  yarn.lock
Labels: Feature

#15 [fix] : yarn 패키지매니저 실행 오류 수정
  yarn.lock
Labels: BugFix

#16 Feature/회원가입 폼 유효성 검증 기능 구현
  src/components/Form/FormAlertErrorBox.tsx
  src/components/Form/FormInput.tsx
  src/components/Form/FormTooltipMessageBox.tsx
  src/components/Form/SignInForm.tsx
  src/components/Form/SignUpForm.tsx
  src/components/Form/index.ts
  src/hooks/useForm.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.css
  src/pages/auth/SignUp.tsx
  src/types/formData.ts
  src/types/user.ts
  tsconfig.json
Labels: Feature, Refactor, BugFix

#19 [fix] : VSCode 에디터상에서 ESLint 작동하지않는 오류 수정
  .eslintrc.cjs
  package.json
  yarn.lock
Labels: BugFix

#20 [feat] : 커뮤니티 페이지 마크업 및 스타일링
  .eslintrc.cjs
  package.json
  public/assets/chevron_dobule_left.svg
  public/assets/chevron_double_right.svg
  public/assets/chevron_down.svg
  public/assets/chevron_left.svg
  public/assets/chevron_right.svg
  public/assets/chevron_up.svg
  src/App.tsx
  src/components/Dropdown.tsx
  src/components/Editor/CustomReactQuill.tsx
  src/components/Form/auth/FormAlertErrorBox.tsx
  src/components/Form/auth/FormInput.tsx
  src/components/Form/auth/FormTooltipMessageBox.tsx
  src/components/Form/auth/SignInForm.tsx
  src/components/Form/auth/SignUpForm.css
  src/components/Form/auth/SignUpForm.tsx
  src/components/Form/index.ts
  src/components/board/BoardArticle.tsx
  src/components/board/BoardList.css
  src/components/board/BoardList.tsx
  src/components/board/BoardSearchForm.tsx
  src/components/board/BoardWriteForm.tsx
  src/components/board/index.ts
  src/components/common/Input.tsx
  src/components/layout/MainLayout.tsx
  src/index.css
  src/main.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/community/BoardView.tsx
  src/pages/community/BoardWrite.css
  src/pages/community/BoardWrite.tsx
  src/pages/community/Forum.tsx
  src/pages/community/Notice.tsx
  src/pages/community/index.ts
  src/styles/custom-components.css
  src/styles/custom-react-quill.css
  src/types/formData.interface.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: Feature, Refactor, Chore

#22 [feat] 검색 페이지 마크업 및 스타일링
  .gitignore
  index.html
  package.json
  src/App.tsx
  src/components/Home/Card.tsx
  src/components/Home/MainTitleIndex.tsx
  src/components/SearchPage/Map.tsx
  src/components/SearchPage/MapHeader.tsx
  src/components/SearchPage/Result.tsx
  src/components/SearchPage/ResultFilter.tsx
  src/components/SearchPage/ResultItem.tsx
  src/components/SearchPage/SearchByCity.tsx
  src/components/SearchPage/SearchByMap.tsx
  src/components/SearchPage/SearchForm.tsx
  src/components/SearchPage/SearchResult.tsx
  src/components/common/Header.tsx
  src/components/common/MenuTitle.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/SideBarItems.tsx
  src/components/layout/Layout.tsx
  src/pages/Home.tsx
  src/pages/SearchPage.tsx
  src/utils/format.tsx
  yarn.lock
Labels: Feature, Design, Add

#26 12 refactor 메인페이지 컴포넌트 및 디자인 수정
  src/components/Home/MainTitleIndex.tsx
  src/components/SearchPage/Map.tsx
  src/components/SearchPage/MapHeader.tsx
  src/components/SearchPage/Result.tsx
  src/components/SearchPage/ResultFilter.tsx
  src/components/SearchPage/ResultItem.tsx
  src/components/SearchPage/SearchByCity.tsx
  src/components/SearchPage/SearchByMap.tsx
  src/components/SearchPage/SearchForm.tsx
  src/components/SearchPage/SearchResult.tsx
  src/components/common/Error.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/MenuTitle.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/SideBarItems.tsx
  src/components/layout/AuthLayout.tsx
  src/components/layout/Layout.tsx
  src/pages/Home.tsx
  src/pages/SearchPage.tsx
Labels: Feature, Refactor, Style, Design

#27 Feature/채팅 페이지 마크업 및 스타일링
  public/assets/clip.svg
  public/assets/default_profile_man.png
  public/assets/default_profile_woman.png
  public/assets/paper_pencil.svg
  public/assets/send.svg
  src/App.tsx
  src/components/Chat/ChatListItem.css
  src/components/Chat/ChatRoomCard.tsx
  src/components/Chat/ChatRoomContainer.tsx
  src/components/Chat/ChatRoomList.tsx
  src/components/Chat/index.ts
  src/components/common/Button.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SocialLoginButtonSet.tsx
  src/components/layout/MainLayout.tsx
  src/pages/chat/ChatLobby.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/index.ts
  src/styles/custom-components.css
  tailwind.config.js
Labels: Feature, Refactor, BugFix

#28 [Chore] : refactoring 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/refactor
Labels: Chore

#30 [refactor] : 회원가입 페이지 코드 및 스타일 리팩토링
  src/components/Form/auth/FormTooltipMessageBox.tsx
  src/components/Form/auth/SignUpForm.tsx
  src/components/layout/AuthLayout.tsx
  src/hooks/useForm.tsx
  src/pages/auth/SignUp.tsx
Labels: Refactor, Design

#33 [feat] : 나의 계약 페이지 마크업 및 스타일링
  public/assets/checkmark.svg
  src/App.tsx
  src/components/Contract/ContractPDFForm.css
  src/components/Contract/ContractPDFForm.tsx
  src/components/Contract/index.ts
  src/components/ProgressIndicator/ProgressBar.tsx
  src/components/ProgressIndicator/ProgressIndicator.css
  src/components/ProgressIndicator/ProgressIndicator.tsx
  src/components/ProgressIndicator/ProgressStep.tsx
  src/components/common/ScrollProgressBar.tsx
  src/pages/contract/ContractWrite.tsx
  src/pages/contract/index.ts
  src/styles/custom-components.css
  tailwind.config.js
Labels: Feature

#35 [feat] : vite-plugin-mkcert 적용
  package.json
  vite.config.ts
  yarn.lock
Labels: Feature, Add

#38 [feat] : 검색 페이지 기능 구현 및 리팩토링
  index.html
  package.json
  src/App.tsx
  src/api/http.ts
  src/api/search.api.ts
  src/components/SearchPage/Map.tsx
  src/components/SearchPage/MapHeader.tsx
  src/components/SearchPage/ResultFilter.tsx
  src/components/SearchPage/SearchByCity.tsx
  src/components/SearchPage/SearchForm.tsx
  src/hooks/useSearch.tsx
  src/pages/SearchPage.tsx
  src/types/formData.interface.ts
  src/types/searchResult.model.ts
Labels: Feature, Refactor, Style, Add

#39 Feature/로그인 및 회원가입 페이지 인증 기능 구현
  src/api/auth/index.ts
  src/api/auth/reissueToken.ts
  src/api/auth/signIn.ts
  src/api/auth/signUp.ts
  src/api/http.ts
  src/components/Form/auth/SignInForm.tsx
  src/components/Form/auth/SignUpForm.tsx
  src/constants/api.ts
  src/hooks/useForm.tsx
  src/store/useAccessTokenStore.ts
  src/types/authApi.type.ts
  src/types/formData.interface.ts
  src/vite-env.d.ts
  vite.config.ts
  yarn.lock
Labels: Feature, Refactor
