Repository PatientPaI/patientpal-frontend, pull requests merged in 2024-08, with the labels that each got.

#72 [feat] : 유저 토큰 정보와 프로필 등록 연결 및 매칭리스트 버그 수정
  src/api/profile.api.ts
  src/api/search.api.ts
  src/components/MyPage/Profile/MatchingListControls.tsx
  src/components/MyPage/Profile/ProfileDetailForm.tsx
  src/components/MyPage/Profile/ProfileModifyForm.tsx
  src/components/SearchPage/MapHeader.tsx
  src/components/SearchPage/Result.tsx
  src/components/SearchPage/ResultItem.tsx
  src/components/SearchPage/SearchForm.tsx
  src/components/SearchPage/SearchResult.tsx
  src/hooks/useProfile.tsx
  src/pages/SearchPage.tsx
  src/types/api/profile.ts
  src/types/searchResult.model.ts
Labels: Feature, BugFix

#70 [refactor] : 커뮤니티 페이지 리팩토링
  src/App.tsx
  src/components/Contract/ContractPDFForm.tsx
  src/components/Form/contract/ContractForm.tsx
  src/components/board/Board.tsx
  src/components/board/BoardArticle.css
  src/components/board/BoardArticle.tsx
  src/components/board/BoardList.tsx
  src/components/board/BoardListItem.tsx
  src/components/board/BoardPagination.tsx
  src/components/board/BoardWriteForm.tsx
  src/components/board/index.ts
  src/constants/api/index.ts
  src/pages/community/BoardModify.tsx
  src/pages/community/BoardView.tsx
  src/pages/community/BoardWrite.tsx
  src/pages/community/Forum.tsx
  src/pages/community/FreeBoard.tsx
  src/pages/community/Notice.tsx
  src/pages/community/NoticeBoard.tsx
  src/pages/community/index.ts
  src/pages/community/loader.ts
  src/routes/router.tsx
  src/services/BoardService.ts
  src/store/useAuthStore.ts
  src/styles/custom-components.css
  src/types/api/auth.ts
  src/types/api/board.ts
  src/types/api/match.ts
  src/types/formData.interface.ts
  src/types/user.ts
  src/utils/getBoardType.ts
Labels: Refactor

#76 [refactor] : 매칭기록 페이지 코드 리팩토링
  public/assets/contract_search.svg
  public/assets/cross_black.svg
  src/components/Contract/ContractPDFForm.css
  src/components/Contract/ContractPDFForm.tsx
  src/components/Modal/ContractViewModal.tsx
  src/components/Modal/index.ts
  src/components/MyPage/MatchRecord/MatchRecordList.css
  src/components/MyPage/MatchRecord/MatchRecordList.tsx
  src/components/common/Modal.tsx
  src/hooks/useModal.tsx
  src/pages/mypage/MatchRecordPage.tsx
  src/services/MatchService.ts
  src/styles/custom-components.css
  tailwind.config.js
Labels: Refactor

#77 [refactor] : 로그인회원가입 페이지 코드 리팩토링
  package.json
  public/assets/cross_black.svg
  public/assets/default_profile.jpg
  public/assets/unknown_profile.jpg
  src/components/Form/FormCheckbox.tsx
  src/components/Form/auth/FormInput.tsx
  src/components/Form/auth/SignInForm.tsx
  src/components/Form/auth/SignUpForm.tsx
  src/components/Modal/FeedbackModal.tsx
  src/components/Modal/index.ts
  src/components/MyPage/MatchRecord/MatchRecordList.tsx
  src/components/ProtectedRoute.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/components/layout/AuthLayout.tsx
  src/components/layout/Layout.tsx
  src/constants/api/index.ts
  src/hooks/hook.tsx
  src/hooks/useModal.tsx
  src/services/AuthService.ts
  src/store/store.tsx
  src/types/api/auth.ts
  src/types/usertype.tsx
  src/utils/getUserIdFromLocalStorage.ts
  yarn.lock
Labels: Feature, Refactor, BugFix

#79 [refactor] : 공지사항 게시판 디자인 수정
  public/assets/speaker_notice.svg
  src/components/board/Board.tsx
  src/components/board/BoardList.css
  src/components/board/BoardList.tsx
  src/components/board/BoardListItem.tsx
Labels: Refactor, Design

#83 [fix] : 검출된 타입 오류 수정
  src/components/Chat/ChatRoomContainer.tsx
  src/components/Contract/ContractPDFForm.tsx
  src/components/Modal/FeedbackModal.tsx
Labels: BugFix

#87 [fix] : 프로필 버그 수정
  src/api/profile.api.ts
  src/components/MyPage/Profile/MatchingListControls.tsx
  src/components/MyPage/Profile/ProfileDetailForm.tsx
  src/components/MyPage/Profile/ProfileModifyForm.tsx
  src/types/api/profile.ts
Labels: Refactor, BugFix

#88 [fix] : 사이드바 depth 버그수정
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/SideBarItems.tsx
Labels: BugFix

#90 [fix] : 검색페이지 버그 수정
  public/assets/seoul/map_0.png
  public/assets/seoul/map_1.png
  public/assets/seoul/map_10.png
  public/assets/seoul/map_11.png
  public/assets/seoul/map_12.png
  public/assets/seoul/map_13.png
  public/assets/seoul/map_14.png
  public/assets/seoul/map_15.png
  public/assets/seoul/map_16.png
  public/assets/seoul/map_17.png
  public/assets/seoul/map_18.png
  public/assets/seoul/map_19.png
  public/assets/seoul/map_2.png
  public/assets/seoul/map_20.png
  public/assets/seoul/map_21.png
  public/assets/seoul/map_22.png
  public/assets/seoul/map_23.png
  public/assets/seoul/map_24.png
  public/assets/seoul/map_25.png
  public/assets/seoul/map_3.png
  public/assets/seoul/map_4.png
  public/assets/seoul/map_5.png
  public/assets/seoul/map_6.png
  public/assets/seoul/map_7.png
  public/assets/seoul/map_8.png
  public/assets/seoul/map_9.png
  src/components/MyPage/FindAddressButton.tsx
  src/components/MyPage/Profile/ProfileDetailForm.tsx
  src/components/SearchPage/Map.tsx
  src/components/SearchPage/MapHeader.tsx
  src/components/SearchPage/ResultItem.tsx
  src/components/SearchPage/SearchByCity.tsx
  src/components/SearchPage/SearchByMap.tsx
  src/components/SearchPage/SearchForm.tsx
  src/components/SearchPage/SearchResultModal.tsx
Labels: BugFix, Design, Add

#93 [feature] : 회원가입 시, 아이디 중복확인 기능 구현
  src/App.tsx
  src/components/Form/auth/SignInForm.tsx
  src/components/Form/auth/SignUpForm.tsx
  src/components/board/Board.tsx
  src/components/board/BoardArticle.tsx
  src/components/board/BoardWriteForm.tsx
  src/components/common/Header.tsx
  src/constants/api/index.ts
  src/pages/community/loader.ts
  src/services/AuthService.ts
  src/services/BoardService.ts
  src/services/MemberService.ts
  src/services/index.ts
  src/types/api/auth.ts
  src/types/api/member.ts
  src/types/formData.interface.ts
Labels: Feature, Refactor

#94 [fix] : 타입 오류 수정
  src/api/profile.api.ts
  src/api/search.api.ts
  src/components/Home/Card.tsx
  src/components/Home/MainTitleIndex.tsx
  src/components/MyPage/CardMenu.tsx
  src/components/MyPage/FindAddressButton.tsx
  src/components/MyPage/Profile/ProfileDetailForm.tsx
  src/components/MyPage/Profile/ProfileModifyForm.tsx
  src/components/SearchPage/Map.tsx
  src/components/SearchPage/MapHeader.tsx
  src/components/SearchPage/Result.tsx
  src/components/SearchPage/ResultFilter.tsx
  src/components/SearchPage/ResultItem.tsx
  src/components/SearchPage/SearchByCity.tsx
  src/components/SearchPage/SearchByMap.tsx
  src/components/SearchPage/SearchForm.tsx
  src/components/SearchPage/SearchResultList.tsx
  src/components/SearchPage/SearchResultModal.tsx
  src/components/common/Error.tsx
  src/components/common/MenuTitle.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/SideBarItems.tsx
  src/constants/api/index.ts
  src/hooks/useProfile.tsx
  src/hooks/useSearch.tsx
  src/pages/Home.tsx
  src/pages/SearchPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/ProfilePage.tsx
  src/pages/mypage/ReviewPage.tsx
  src/types/api/profile.ts
Labels: BugFix

#96 [refactor] 로그인 유저 데이터 수신 타입 수정
  src/components/Form/contract/ContractForm.tsx
  src/components/common/Header.tsx
  src/services/MemberService.ts
  src/store/useAuthStore.ts
  src/types/api/member.ts
Labels: Refactor

#99 [fix] : 배포 환경에서 새로고침 시, 404 not found 나오는 에러 수정
  vercel.json
Labels: BugFix

#108 [fix] : 프로필 등록 페이지 버그 수정
  src/components/MyPage/Profile/ProfileDetailForm.tsx
  src/components/MyPage/Profile/ProfileModifyForm.tsx
Labels: BugFix

#106 [feat] : 커스텀 alert confirm 모달 기능 구현
  src/App.tsx
  src/components/Form/auth/SignUpForm.tsx
  src/components/Modal/FeedbackModal.tsx
  src/components/ProtectedRoute.tsx
  src/components/board/BoardArticle.tsx
  src/hooks/useModal.tsx
  src/store/useModalStore.ts
Labels: Feature, Refactor

#104 [refactor ] : 계약서 작성 및 매칭기록 페이지 리팩토링
  public/assets/review_star_empty.png
  public/assets/review_star_full.png
  public/assets/review_write.svg
  src/components/Form/contract/ContractForm.css
  src/components/Form/contract/ContractForm.tsx
  src/components/Form/contract/ContractUserInfo.tsx
  src/components/Modal/ContractViewModal.tsx
  src/components/Modal/ReviewWriteModal.tsx
  src/components/MyPage/MatchRecord/MatchRecordList.tsx
  src/pages/contract/ContractWrite.tsx
  src/pages/mypage/MatchRecordPage.tsx
  src/types/api/match.ts
Labels: Feature, Refactor, BugFix

#109 [fix] : 프로필 등록 페이지 버그 수정
  src/components/MyPage/Profile/ProfileDetailForm.tsx
  src/components/MyPage/Profile/ProfileModifyForm.tsx
Labels: BugFix

#111 [fix] : FeedbackModal props 변경으로 인한 렌더링 오류 수정
  src/components/Form/contract/ContractForm.tsx
  src/components/Form/contract/ContractUserInfo.tsx
  src/components/Modal/ContractViewModal.tsx
  src/components/MyPage/MatchRecord/MatchRecordList.tsx
  src/components/board/BoardArticle.tsx
  src/components/board/BoardSearchForm.tsx
  src/components/board/BoardWriteForm.tsx
  src/components/common/Modal.tsx
  src/pages/contract/ContractWrite.tsx
  src/pages/mypage/MatchRecordPage.tsx
Labels: BugFix

#114 [fix] : 프로필 정보 최신화 버그 수정
  src/components/MyPage/Profile/ProfileModifyForm.tsx
Labels: Feature, BugFix

#115 [refactor] : 전체적인 페이지별 접근 권한 변경
  src/components/ProtectedRoute.tsx
  src/components/board/Board.tsx
  src/components/board/BoardArticle.tsx
  src/components/board/BoardListItem.tsx
  src/components/board/BoardWriteForm.tsx
  src/pages/community/BoardModify.tsx
  src/pages/community/BoardView.tsx
  src/pages/community/BoardWrite.tsx
  src/routes/router.tsx
  src/types/api/board.ts
Labels: Refactor

#120 [refactor] : 로고 및 푸터 수정
  public/assets/Footer Logo.png
  public/assets/logo-footer.png
  public/assets/logo-main.png
  src/components/common/Footer.tsx
Labels: Refactor, Add

#116 [feat] : 비로그인시 검색페이지 동작 구현
  src/api/search.api.ts
  src/components/SearchPage/MapHeader.tsx
  src/components/SearchPage/Result.tsx
  src/components/SearchPage/ResultItem.tsx
  src/components/SearchPage/SearchForm.tsx
  src/hooks/useSearch.ts
  src/hooks/useSearch.tsx
  src/pages/SearchPage.tsx
Labels: Feature

#122 [feat] : 1대1 채팅 기능 구현
  index.html
  package.json
  src/api/httpClient.ts
  src/api/stompClient.ts
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatListItem.css
  src/components/Chat/ChatListItem.tsx
  src/components/Chat/ChatMessageForm.tsx
  src/components/Chat/ChatMessenger.tsx
  src/components/Chat/ChatRoomCard.tsx
  src/components/Chat/ChatRoomContainer.tsx
  src/components/Chat/ChatRoomList.tsx
  src/components/Chat/ChatRoomListItem.tsx
  src/components/Chat/index.ts
  src/components/Form/contract/ContractForm.tsx
  src/components/SearchPage/ResultItem.tsx
  src/components/board/BoardArticle.tsx
  src/components/board/BoardListItem.tsx
  src/components/common/Header.tsx
  src/constants/api/index.ts
  src/context/ChatContextProvider.tsx
  src/hooks/useChat.ts
  src/hooks/useChatContext.ts
  src/hooks/useForm.ts
  src/pages/chat/ChatLobby.tsx
  src/pages/chat/ChatRoom.tsx
  src/routes/router.tsx
  src/services/ChatService.ts
  src/services/index.ts
  src/store/useNotificationStore.ts
  src/types/api/board.ts
  src/types/api/chat.ts
  src/types/api/common.ts
  src/types/api/member.ts
  src/utils/convertDatetime.ts
  src/utils/toLocaleISOString.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: Feature, Refactor, Add

#125 [feat] : 알림 기능 구현
  package.json
  src/App.tsx
  src/components/Modal/NotificationModal.tsx
  src/components/Modal/index.ts
  src/components/MyPage/MatchRecord/MatchRecordList.tsx
  src/components/common/Header.tsx
  src/constants/api/index.ts
  src/pages/mypage/MatchRecordPage.tsx
  src/services/AuthService.ts
  src/services/NotificationService.ts
  src/services/index.ts
  src/store/useNotificationStore.ts
  yarn.lock
Labels: Feature, Refactor, BugFix
