Repository PatientPaI/patientpal-frontend, pull requests merged in 2024-07, with the labels that each got.

#41 [feat] : 설정 페이지 마크업 및 스타일링
  src/App.tsx
  src/components/layout/SettingLayout.tsx
  src/components/setting/CardMenu.tsx
  src/pages/setting/MatchRecordPage.tsx
  src/pages/setting/ModifyPage.tsx
  src/pages/setting/ReviewPage.tsx
  src/pages/setting/SettingPage.tsx
Labels: Feature, Design

#45 [refactor] 인증 api 호출 구조 리팩토링
  src/api/auth/authApi.ts
  src/api/auth/reissueToken.ts
  src/api/auth/signIn.ts
  src/api/auth/signUp.ts
  src/components/Form/auth/SignInForm.tsx
  src/components/Form/auth/SignUpForm.tsx
  src/constants/api.ts
  src/services/AuthService.ts
  src/types/authApi.type.ts
Labels: Refactor

#47 [refactor] : axios 인스턴스 관련 코드 리팩토링
  src/api/auth/authApi.ts
  src/api/auth/index.ts
  src/api/http.ts
  src/api/httpClient.ts
  src/constants/api/index.ts
  src/services/AuthService.ts
  src/types/api/auth.ts
  src/types/api/common.ts
  src/types/authApi.type.ts
  src/utils/createAxiosInstance.ts
Labels: Refactor

#50 [refactor] : 계약서 작성 페이지 디자인 변경
  src/App.tsx
  src/components/Form/contract/ContractForm.css
  src/components/Form/contract/ContractForm.tsx
  src/pages/contract/ContractWrite.tsx
  src/styles/custom-components.css
  src/types/formData.interface.ts
  src/utils/convertDatetime.ts
Labels: Refactor, Design

#52 [feat] : 토큰 재발급 기능 구현
  src/App.tsx
  src/components/ProtectedRoute.tsx
  src/services/AuthService.ts
  src/store/useAuthStore.ts
Labels: Feature, Refactor

#58 [feat] : 계약서 전송 기능 구현
  src/App.tsx
  src/api/httpClient.ts
  src/components/Contract/ContractPDFForm.tsx
  src/components/Form/contract/ContractForm.css
  src/components/Form/contract/ContractForm.tsx
  src/components/Form/contract/ContractUserInfo.tsx
  src/constants/api/index.ts
  src/pages/contract/ContractWrite.tsx
  src/services/BoardService.ts
  src/services/MatchService.ts
  src/types/api/match.ts
  src/types/formData.interface.ts
  src/utils/validateObject.ts
Labels: Feature, Refactor, BugFix

#60 [fix] : access 토큰 오류 수정
  src/api/profile.api.ts
  src/components/MyPage/Profile/MatchingListControls.tsx
  src/components/MyPage/Profile/ProfileModifyForm.tsx
  src/hooks/useProfile.tsx
  src/pages/mypage/ProfilePage.tsx
Labels: Feature, Refactor, BugFix

#63 [fix] : 환자 프로필 등록 오류 수정
  src/api/profile.api.ts
  src/components/MyPage/Profile/ProfileModifyForm.tsx
Labels: BugFix

#65 [refactor] : 사용자 인증 상태관리 함수 리팩토링
  src/App.tsx
  src/components/Form/auth/SignInForm.tsx
  src/components/Form/auth/SignUpForm.tsx
  src/components/ProtectedRoute.tsx
  src/constants/api/index.ts
  src/services/AuthService.ts
  src/store/useAuthStore.ts
  src/types/api/auth.ts
  src/utils/decodeTokenPayload.ts
Labels: Refactor

#66 Feature/계약서 조회 기능 구현
  index.html
  public/assets/arrow_receive.svg
  public/assets/arrow_send.svg
  public/assets/calendar.svg
  public/assets/contract_search.svg
  public/assets/cross_white.svg
  public/assets/won.svg
  src/App.tsx
  src/components/Contract/ContractPDFForm.css
  src/components/Contract/ContractPDFForm.tsx
  src/components/Form/contract/ContractForm.tsx
  src/components/common/Modal.tsx
  src/components/common/SideBar/SideBar.tsx
  src/constants/api/index.ts
  src/hooks/useModal.ts
  src/pages/contract/ContractWrite.tsx
  src/pages/mypage/MatchRecordPage.tsx
  src/services/MatchService.ts
  src/store/useModalStore.ts
  src/types/api/match.ts
  tailwind.config.js
Labels: Feature, Refactor, BugFix

#69 [fix] : api 엔드포인트 변경에 따른 오류 수정
  src/services/AuthService.ts
Labels: BugFix
