Repository PatientPaI/patientpal-frontend, pull requests merged in 2024-09, with the labels that each got.

#128 [feature] : 메인 페이지 주요 기능 구현
  public/assets/right_circle_icon.png
  public/assets/user_recommend_blur.png
  src/components/Home/Card.tsx
  src/components/Home/NoticePreview.tsx
  src/components/Home/TopRatedCaregivers.tsx
  src/components/Home/UserRecommendation.tsx
  src/components/Home/index.ts
  src/components/SearchPage/ResultItem.tsx
  src/components/board/BoardArticle.tsx
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/constants/api/index.ts
  src/pages/Home.tsx
  src/services/MemberService.ts
  src/services/ReviewService.ts
  src/services/index.ts
  src/types/api/member.ts
  src/types/api/review.ts
Labels: Feature, Refactor

#124 [feat] : 현재 자신의 위치 마커로 표시하는 기능 구현
  src/components/SearchPage/Map.tsx
Labels: Feature

#129 [fix] : 우수 간병인 제대로 표시되지 않는 버그 및 타입 검사 오류 수정
  src/components/Home/TopRatedCaregivers.tsx
  src/components/Home/UserRecommendation.tsx
  src/components/SearchPage/Map.tsx
Labels: BugFix

#131 [refactor] : 빌드 파일 및 이미지 용량 최적화
  .eslintrc.cjs
  package.json
  src/components/ProtectedRoute.tsx
  src/components/board/Board.tsx
  src/components/layout/AuthLayout.tsx
  src/components/layout/Layout.tsx
  src/components/layout/MainLayout.tsx
  src/context/ChatContextProvider.tsx
  src/pages/Home.tsx
  src/pages/SearchPage.tsx
  src/pages/auth/SignIn.tsx
  src/pages/auth/SignUp.tsx
  src/pages/auth/index.ts
  src/pages/chat/ChatLobby.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/index.ts
  src/pages/community/BoardModify.tsx
  src/pages/community/BoardView.tsx
  src/pages/community/BoardWrite.tsx
  src/pages/community/FreeBoard.tsx
  src/pages/community/NoticeBoard.tsx
  src/pages/community/index.ts
  src/pages/community/loader.ts
  src/pages/contract/ContractWrite.tsx
  src/pages/contract/index.ts
  src/pages/mypage/MatchRecordPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/ProfilePage.tsx
  src/pages/mypage/ReviewPage.tsx
  src/routes/router.tsx
  vite.config.ts
  yarn.lock
Labels: Feature, Refactor

#133 [bugfix] : 빌드 오류 수정
  src/components/Form/FormCheckbox.tsx
  src/components/Form/auth/FormInput.tsx
Labels: BugFix
